# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('requisite', models.CharField(blank=True, max_length=200, null=True)),
                ('next_context', models.CharField(blank=True, max_length=200, null=True)),
                ('family', models.CharField(max_length=200)),
                ('family_importance', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
