# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-16 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_possiblecontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('how', models.TextField(max_length=300)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbox.PossibleContext')),
            ],
        ),
    ]
