# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-10 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_contextdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdetail',
            name='messageHindi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
