# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_contextdetail_messagehindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdetail',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
