# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-29 19:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0010_courselength'),
        ('learning', '0003_auto_20190310_1346'),
        ('chatbox', '0006_auto_20190315_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_sovle', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('to_solve', models.IntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.SubjectChapters')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_length', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('chapters', models.ManyToManyField(to='learning.SubjectChapters')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
            ],
        ),
        migrations.AddField(
            model_name='chapterplan',
            name='studyPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbox.StudyPlan'),
        ),
    ]
