# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0010_courselength'),
        ('chatbox', '0007_auto_20190330_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestChatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
            ],
        ),
    ]
