# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0008_latestchatdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='current_chapter_code',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='current_chapter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='current_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
