# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-17 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscklasstest',
            name='mock_test',
            field=models.NullBooleanField(default=False),
        ),
    ]
