# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0003_auto_20190220_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscklasstest',
            name='typeTest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
