# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0008_auto_20190223_1228'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.URLField(blank=True, max_length=500, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher')),
            ],
        ),
    ]
