# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-10 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_teacheruploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruploadedimage',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TeacherUploadedImage',
        ),
    ]
