# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-07 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0002_studentsubjectaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('examDate', models.DateTimeField()),
            ],
        ),
    ]
