# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0003_nextexamdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessKey', models.CharField(max_length=500)),
                ('secretKey', models.CharField(max_length=500)),
            ],
        ),
    ]
