# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0007_auto_20190219_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='promocode',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.PromoInstitute'),
        ),
    ]
